# Generated by Django 3.0 on 2022-01-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0056_auto_20210702_2207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseworkassessment',
            unique_together=set(),
        ),
    ]
